version: "3.7"

services:

    redis_queue:
        image: redis:6.0.1-alpine
        restart: always
        container_name: redis_queue
    
    rabbit_queue:
        image: rabbitmq:3.8.3-alpine
        restart: always
        container_name: rabbit_queue

    web_app:
        build: ./queue_app
        command: python app.py
        container_name: web_app
        restart: always
        expose:
            - 5000
        ports: 
            - 8081:5000
        depends_on: 
            - redis_queue
            - rabbit_queue
    
    worker:
        build: ./queue_app
        command: celery -A celery_worker worker -l info -Q default,low_priority,high_priority
        container_name: worker
        restart: always
        depends_on: 
            - redis_queue
            - rabbit_queue